[package]
name = "example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
use-https = { version = "0.1.0", git = "https://github.com/Maki325/use-https.git", tag = "v0.1.0" }
